dist: trusty
services:
  - docker
before_install:
- sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl
- sudo echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list
- sudo add-apt-repository ppa:gns3/qemu -y
- wget -q -O - https://dl.google.com/linux/
- sudo linux_signing_key.pub | sudo apt-key add -
- sudo apt-get -qq update
script:
- sudo ./build-docker.sh
- sudo CONTINUE=1 ./build-docker.sh
before_deploy:
- export RELEASE_FILE_NAME="deploy/image_"$(date +%Y-%m-%d)"}"-HoneyPi.zip"
- export MD5=$(md5sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- export SHA1=$(sha1sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- touch MD5:"${MD5}"
- touch SHA1:"${SHA1}"
- echo "deploying $RELEASE_FILE_NAME to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: $RELEASE_FILE_NAME
  on:
    tags: true
    repo: HoneyPi/HoneyPi-Build-Raspbian
  file_glob: true
  skip_cleanup: true
