dist: trusty
sudo: required
language: bash
addons:
  apt:
    packages:
      - qemu
      - qemu-user-static
      - binfmt-support
      - parted
      - wget
      - dosfstools
      - zip
      - git
      - curl
      - coreutils
      - quilt
      - debootstrap
      - bsdtar
services:
  - docker
before_install:
- sudo apt-get -y install coreutils 
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- git clone https://github.com/RPi-Distro/pi-gen
- cd pi-gen
- git fetch && git fetch --tags
- git checkout 2020-12-02-raspbian-buster
- cd ..
- cp config pi-gen/config
- cp -R stage-honeypi pi-gen/stage-honeypi
- cd pi-gen
- sudo ./build.sh
before_deploy:
- export RELEASE_FILE_NAME="deploy/image_"$(date +%Y-%m-%d)"}"-HoneyPi.zip"
- export MD5=$(md5sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- export SHA1=$(sha1sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- touch MD5:"${MD5}"
- touch SHA1:"${SHA1}"
- echo "deploying $RELEASE_FILE_NAME to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: $RELEASE_FILE_NAME
  on:
    tags: true
    repo: HoneyPi/HoneyPi-Build-Raspbian
  file_glob: true
  skip_cleanup: true
  draft: false
