os: linux
dist: xenial
language: shell
version: ~> 1.0
addons:
  apt:
    update: true
    packages:
      - qemu
      - qemu-user-static
      - binfmt-support
      - parted
      - wget
      - dosfstools
      - zip
      - git
      - curl
      - coreutils
      - quilt
      - debootstrap
      - bsdtar
services:
#  - docker
before_install:
- sudo apt-get update
install:
# prepare qemu
#- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc
script:
- git clone https://github.com/RPi-Distro/pi-gen
- cd pi-gen
- git fetch && git fetch --tags
- git checkout 2020-12-02-raspbian-buster
- cd ..
- cp config pi-gen/config
- cp -R stage-honeypi pi-gen/stage-honeypi
- cd pi-gen
- travis_wait 30 sudo ./build.sh
before_deploy:
- export RELEASE_FILE_NAME="deploy/image_"$(date +%Y-%m-%d)"}"-HoneyPi.zip"
- export MD5=$(md5sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- export SHA1=$(sha1sum ${RELEASE_FILE_NAME} | cut -d ' ' -f 1)
- touch MD5:"${MD5}"
- touch SHA1:"${SHA1}"
- echo "deploying $RELEASE_FILE_NAME to GitHub releases"
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: $RELEASE_FILE_NAME
  edge: true # opt in to dpl v2
  on:
    tags: true
    repo: HoneyPi/HoneyPi-Build-Raspbian
  file_glob: true
  cleanup: true
  draft: false
